language: php

php:
  - 7.2
  - 7.4

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
