language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1
    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"

  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"

notifications:
  email: false
